using System.Collections.Generic;
using StockPicker.Models;

namespace StockPicker.Services
{
    /// <summary>
    /// Hard-coded constituent lists for indices that don't require a network fetch.
    ///
    /// Last verified: April 2025.
    /// Index memberships change periodically; if precision matters, verify against
    /// the official index provider (S&amp;P Global, Nasdaq, etc.) and update this file.
    /// </summary>
    public static class BuiltInUniverses
    {
        // ── Dow Jones Industrial Average (DJIA) — 30 components ──────────────────

        /// <summary>
        /// DJIA constituents as of April 2025.
        /// Notable recent changes: AMZN replaced WBA (Feb 2024), NVDA replaced INTC (Nov 2024).
        /// </summary>
        public static IReadOnlyList<Stock> Dow30 { get; } = new List<Stock>
        {
            new() { Symbol = "AAPL",  Name = "Apple Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "AMGN",  Name = "Amgen Inc.",                    Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "AMZN",  Name = "Amazon.com Inc.",               Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "AXP",   Name = "American Express Co.",          Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "BA",    Name = "Boeing Co.",                    Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "CAT",   Name = "Caterpillar Inc.",              Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "CRM",   Name = "Salesforce Inc.",               Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "CSCO",  Name = "Cisco Systems Inc.",            Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "CVX",   Name = "Chevron Corp.",                 Sector = "Energy",                 Exchange = "NYSE"   },
            new() { Symbol = "DIS",   Name = "Walt Disney Co.",               Sector = "Communication Services", Exchange = "NYSE"   },
            new() { Symbol = "DOW",   Name = "Dow Inc.",                      Sector = "Materials",              Exchange = "NYSE"   },
            new() { Symbol = "GS",    Name = "Goldman Sachs Group Inc.",      Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "HD",    Name = "Home Depot Inc.",               Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "HON",   Name = "Honeywell International Inc.",  Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "IBM",   Name = "IBM Corp.",                     Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "JNJ",   Name = "Johnson & Johnson",             Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "JPM",   Name = "JPMorgan Chase & Co.",          Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "KO",    Name = "Coca-Cola Co.",                 Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "MCD",   Name = "McDonald's Corp.",              Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "MMM",   Name = "3M Co.",                        Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "MRK",   Name = "Merck & Co. Inc.",              Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "MSFT",  Name = "Microsoft Corp.",               Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "NKE",   Name = "Nike Inc.",                     Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "NVDA",  Name = "NVIDIA Corp.",                  Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "PG",    Name = "Procter & Gamble Co.",          Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "SHW",   Name = "Sherwin-Williams Co.",          Sector = "Materials",              Exchange = "NYSE"   },
            new() { Symbol = "TRV",   Name = "Travelers Companies Inc.",      Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "UNH",   Name = "UnitedHealth Group Inc.",       Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "V",     Name = "Visa Inc.",                     Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "WMT",   Name = "Walmart Inc.",                  Sector = "Consumer Staples",       Exchange = "NYSE"   },
        };

        // ── S&P 100 — 100 largest S&P 500 companies by market cap ────────────────

        /// <summary>
        /// S&amp;P 100 constituents as of April 2025 (OEX index components).
        /// Ranked approximately by market capitalisation; exact rank varies daily.
        /// </summary>
        public static IReadOnlyList<Stock> SP100 { get; } = new List<Stock>
        {
            new() { Symbol = "AAPL",  Name = "Apple Inc.",                      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "MSFT",  Name = "Microsoft Corp.",                 Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "NVDA",  Name = "NVIDIA Corp.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "AMZN",  Name = "Amazon.com Inc.",                 Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "GOOGL", Name = "Alphabet Inc. Class A",           Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "META",  Name = "Meta Platforms Inc.",             Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "GOOG",  Name = "Alphabet Inc. Class C",           Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "TSLA",  Name = "Tesla Inc.",                      Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "BRK.B", Name = "Berkshire Hathaway Inc. Class B", Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "LLY",   Name = "Eli Lilly and Co.",               Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "AVGO",  Name = "Broadcom Inc.",                   Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "WMT",   Name = "Walmart Inc.",                    Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "JPM",   Name = "JPMorgan Chase & Co.",            Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "V",     Name = "Visa Inc.",                       Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "UNH",   Name = "UnitedHealth Group Inc.",         Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "XOM",   Name = "Exxon Mobil Corp.",               Sector = "Energy",                 Exchange = "NYSE"   },
            new() { Symbol = "MA",    Name = "Mastercard Inc.",                 Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "ORCL",  Name = "Oracle Corp.",                    Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "COST",  Name = "Costco Wholesale Corp.",          Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "HD",    Name = "Home Depot Inc.",                 Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "PG",    Name = "Procter & Gamble Co.",            Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "JNJ",   Name = "Johnson & Johnson",               Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "ABBV",  Name = "AbbVie Inc.",                     Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "BAC",   Name = "Bank of America Corp.",           Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "KO",    Name = "Coca-Cola Co.",                   Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "MRK",   Name = "Merck & Co. Inc.",                Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "NFLX",  Name = "Netflix Inc.",                    Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "CVX",   Name = "Chevron Corp.",                   Sector = "Energy",                 Exchange = "NYSE"   },
            new() { Symbol = "CRM",   Name = "Salesforce Inc.",                 Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "AMD",   Name = "Advanced Micro Devices Inc.",     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "TMO",   Name = "Thermo Fisher Scientific Inc.",   Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "ACN",   Name = "Accenture plc",                   Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "LIN",   Name = "Linde plc",                       Sector = "Materials",              Exchange = "NASDAQ" },
            new() { Symbol = "MCD",   Name = "McDonald's Corp.",                Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "CSCO",  Name = "Cisco Systems Inc.",              Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "ABT",   Name = "Abbott Laboratories",             Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "PEP",   Name = "PepsiCo Inc.",                    Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "IBM",   Name = "IBM Corp.",                       Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "GE",    Name = "GE Aerospace",                   Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "NOW",   Name = "ServiceNow Inc.",                 Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "ADBE",  Name = "Adobe Inc.",                      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "PM",    Name = "Philip Morris International",     Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "DHR",   Name = "Danaher Corp.",                   Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "ISRG",  Name = "Intuitive Surgical Inc.",         Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "TXN",   Name = "Texas Instruments Inc.",          Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "INTU",  Name = "Intuit Inc.",                     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "VZ",    Name = "Verizon Communications Inc.",     Sector = "Communication Services", Exchange = "NYSE"   },
            new() { Symbol = "GS",    Name = "Goldman Sachs Group Inc.",        Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "AMGN",  Name = "Amgen Inc.",                      Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "CAT",   Name = "Caterpillar Inc.",                Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "CMCSA", Name = "Comcast Corp.",                   Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "BLK",   Name = "BlackRock Inc.",                  Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "RTX",   Name = "RTX Corp.",                       Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "AXP",   Name = "American Express Co.",            Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "SPGI",  Name = "S&P Global Inc.",                 Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "T",     Name = "AT&T Inc.",                       Sector = "Communication Services", Exchange = "NYSE"   },
            new() { Symbol = "PFE",   Name = "Pfizer Inc.",                     Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "MS",    Name = "Morgan Stanley",                  Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "NEE",   Name = "NextEra Energy Inc.",             Sector = "Utilities",              Exchange = "NYSE"   },
            new() { Symbol = "HON",   Name = "Honeywell International Inc.",    Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "UBER",  Name = "Uber Technologies Inc.",          Sector = "Technology",             Exchange = "NYSE"   },
            new() { Symbol = "LOW",   Name = "Lowe's Companies Inc.",           Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "AMAT",  Name = "Applied Materials Inc.",          Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "UNP",   Name = "Union Pacific Corp.",             Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "C",     Name = "Citigroup Inc.",                  Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "BA",    Name = "Boeing Co.",                      Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "DE",    Name = "Deere & Co.",                     Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "BMY",   Name = "Bristol-Myers Squibb Co.",        Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "SCHW",  Name = "Charles Schwab Corp.",            Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "ELV",   Name = "Elevance Health Inc.",            Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "MDT",   Name = "Medtronic plc",                   Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "LMT",   Name = "Lockheed Martin Corp.",           Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "PLD",   Name = "Prologis Inc.",                   Sector = "Real Estate",            Exchange = "NYSE"   },
            new() { Symbol = "MO",    Name = "Altria Group Inc.",               Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "SYK",   Name = "Stryker Corp.",                   Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "MMC",   Name = "Marsh & McLennan Companies",      Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "CB",    Name = "Chubb Ltd.",                      Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "TJX",   Name = "TJX Companies Inc.",              Sector = "Consumer Discretionary", Exchange = "NYSE"   },
            new() { Symbol = "DUK",   Name = "Duke Energy Corp.",               Sector = "Utilities",              Exchange = "NYSE"   },
            new() { Symbol = "ZTS",   Name = "Zoetis Inc.",                     Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "SO",    Name = "Southern Co.",                    Sector = "Utilities",              Exchange = "NYSE"   },
            new() { Symbol = "REGN",  Name = "Regeneron Pharmaceuticals",       Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "ETN",   Name = "Eaton Corp. plc",                 Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "CI",    Name = "The Cigna Group",                 Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "AON",   Name = "Aon plc",                         Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "ITW",   Name = "Illinois Tool Works Inc.",        Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "EQIX",  Name = "Equinix Inc.",                    Sector = "Real Estate",            Exchange = "NASDAQ" },
            new() { Symbol = "NOC",   Name = "Northrop Grumman Corp.",          Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "WM",    Name = "Waste Management Inc.",           Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "GD",    Name = "General Dynamics Corp.",          Sector = "Industrials",            Exchange = "NYSE"   },
            new() { Symbol = "SHW",   Name = "Sherwin-Williams Co.",            Sector = "Materials",              Exchange = "NYSE"   },
            new() { Symbol = "COP",   Name = "ConocoPhillips",                  Sector = "Energy",                 Exchange = "NYSE"   },
            new() { Symbol = "PGR",   Name = "Progressive Corp.",               Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "COF",   Name = "Capital One Financial Corp.",     Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "TGT",   Name = "Target Corp.",                    Sector = "Consumer Staples",       Exchange = "NYSE"   },
            new() { Symbol = "USB",   Name = "U.S. Bancorp",                    Sector = "Financials",             Exchange = "NYSE"   },
            new() { Symbol = "MDLZ",  Name = "Mondelez International Inc.",     Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "HUM",   Name = "Humana Inc.",                     Sector = "Healthcare",             Exchange = "NYSE"   },
            new() { Symbol = "OKE",   Name = "ONEOK Inc.",                      Sector = "Energy",                 Exchange = "NYSE"   },
        };

        // ── NASDAQ-100 (NDX) — 100 largest non-financial NASDAQ companies ─────────

        /// <summary>
        /// NASDAQ-100 constituents as of April 2025.
        /// Rebalanced quarterly by Nasdaq Inc.; dominated by technology and growth sectors.
        /// </summary>
        public static IReadOnlyList<Stock> Nasdaq100 { get; } = new List<Stock>
        {
            new() { Symbol = "AAPL",  Name = "Apple Inc.",                       Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "MSFT",  Name = "Microsoft Corp.",                  Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "NVDA",  Name = "NVIDIA Corp.",                     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "AMZN",  Name = "Amazon.com Inc.",                  Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "META",  Name = "Meta Platforms Inc.",              Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "GOOGL", Name = "Alphabet Inc. Class A",            Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "GOOG",  Name = "Alphabet Inc. Class C",            Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "TSLA",  Name = "Tesla Inc.",                       Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "AVGO",  Name = "Broadcom Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "COST",  Name = "Costco Wholesale Corp.",           Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "NFLX",  Name = "Netflix Inc.",                     Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "ASML",  Name = "ASML Holding NV",                  Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "AMD",   Name = "Advanced Micro Devices Inc.",      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "QCOM",  Name = "QUALCOMM Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "TMUS",  Name = "T-Mobile US Inc.",                 Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "AMGN",  Name = "Amgen Inc.",                       Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "INTU",  Name = "Intuit Inc.",                      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "AMAT",  Name = "Applied Materials Inc.",           Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "CSCO",  Name = "Cisco Systems Inc.",               Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "TXN",   Name = "Texas Instruments Inc.",           Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "PEP",   Name = "PepsiCo Inc.",                     Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "LRCX",  Name = "Lam Research Corp.",               Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "PANW",  Name = "Palo Alto Networks Inc.",          Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "ADI",   Name = "Analog Devices Inc.",              Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "MU",    Name = "Micron Technology Inc.",           Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "KLAC",  Name = "KLA Corp.",                        Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "SNPS",  Name = "Synopsys Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "CDNS",  Name = "Cadence Design Systems Inc.",      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "ORLY",  Name = "O'Reilly Automotive Inc.",         Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "CRWD",  Name = "CrowdStrike Holdings Inc.",        Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "REGN",  Name = "Regeneron Pharmaceuticals Inc.",   Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "MELI",  Name = "MercadoLibre Inc.",                Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "ADSK",  Name = "Autodesk Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "MRVL",  Name = "Marvell Technology Inc.",          Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "FTNT",  Name = "Fortinet Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "CTAS",  Name = "Cintas Corp.",                     Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "MNST",  Name = "Monster Beverage Corp.",           Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "CEG",   Name = "Constellation Energy Corp.",       Sector = "Utilities",              Exchange = "NASDAQ" },
            new() { Symbol = "PAYX",  Name = "Paychex Inc.",                     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "KDP",   Name = "Keurig Dr Pepper Inc.",            Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "CPRT",  Name = "Copart Inc.",                      Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "NXPI",  Name = "NXP Semiconductors NV",           Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "PCAR",  Name = "PACCAR Inc.",                      Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "MCHP",  Name = "Microchip Technology Inc.",        Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "FAST",  Name = "Fastenal Co.",                     Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "ROST",  Name = "Ross Stores Inc.",                 Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "ON",    Name = "ON Semiconductor Corp.",           Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "TEAM",  Name = "Atlassian Corp.",                  Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "DXCM",  Name = "DexCom Inc.",                      Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "ROP",   Name = "Roper Technologies Inc.",          Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "IDXX",  Name = "IDEXX Laboratories Inc.",          Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "AEP",   Name = "American Electric Power Co.",      Sector = "Utilities",              Exchange = "NASDAQ" },
            new() { Symbol = "ODFL",  Name = "Old Dominion Freight Line Inc.",   Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "KHC",   Name = "Kraft Heinz Co.",                  Sector = "Consumer Staples",       Exchange = "NASDAQ" },
            new() { Symbol = "EXC",   Name = "Exelon Corp.",                     Sector = "Utilities",              Exchange = "NASDAQ" },
            new() { Symbol = "VRSK",  Name = "Verisk Analytics Inc.",            Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "FANG",  Name = "Diamondback Energy Inc.",          Sector = "Energy",                 Exchange = "NASDAQ" },
            new() { Symbol = "CSX",   Name = "CSX Corp.",                        Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "BIIB",  Name = "Biogen Inc.",                      Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "DLTR",  Name = "Dollar Tree Inc.",                 Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "GEHC",  Name = "GE HealthCare Technologies Inc.",  Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "ANSS",  Name = "ANSYS Inc.",                       Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "ILMN",  Name = "Illumina Inc.",                    Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "TTWO",  Name = "Take-Two Interactive Software",    Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "ZS",    Name = "Zscaler Inc.",                     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "WDAY",  Name = "Workday Inc.",                     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "EBAY",  Name = "eBay Inc.",                        Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "PYPL",  Name = "PayPal Holdings Inc.",             Sector = "Financials",             Exchange = "NASDAQ" },
            new() { Symbol = "CHTR",  Name = "Charter Communications Inc.",      Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "ULTA",  Name = "Ulta Beauty Inc.",                 Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "SIRI",  Name = "Sirius XM Holdings Inc.",          Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "ABNB",  Name = "Airbnb Inc.",                      Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "DASH",  Name = "DoorDash Inc.",                    Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "ARM",   Name = "Arm Holdings plc",                 Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "DDOG",  Name = "Datadog Inc.",                     Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "OKTA",  Name = "Okta Inc.",                        Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "ALGN",  Name = "Align Technology Inc.",            Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "VRSN",  Name = "VeriSign Inc.",                    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "SWKS",  Name = "Skyworks Solutions Inc.",          Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "MPWR",  Name = "Monolithic Power Systems Inc.",    Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "ZBRA",  Name = "Zebra Technologies Corp.",         Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "JBHT",  Name = "J.B. Hunt Transport Services",     Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "SSNC",  Name = "SS&C Technologies Holdings Inc.",  Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "NTAP",  Name = "NetApp Inc.",                      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "WBD",   Name = "Warner Bros. Discovery Inc.",      Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "EXPE",  Name = "Expedia Group Inc.",               Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "PODD",  Name = "Insulet Corp.",                    Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "GILD",  Name = "Gilead Sciences Inc.",             Sector = "Healthcare",             Exchange = "NASDAQ" },
            new() { Symbol = "HON",   Name = "Honeywell International Inc.",     Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "CMCSA", Name = "Comcast Corp.",                    Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "INTC",  Name = "Intel Corp.",                      Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "GFS",   Name = "GlobalFoundries Inc.",             Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "SMCI",  Name = "Super Micro Computer Inc.",        Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "TTD",   Name = "The Trade Desk Inc.",              Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "LULU",  Name = "Lululemon Athletica Inc.",         Sector = "Consumer Discretionary", Exchange = "NASDAQ" },
            new() { Symbol = "EA",    Name = "Electronic Arts Inc.",             Sector = "Communication Services", Exchange = "NASDAQ" },
            new() { Symbol = "MSTR",  Name = "MicroStrategy Inc.",               Sector = "Technology",             Exchange = "NASDAQ" },
            new() { Symbol = "AXON",  Name = "Axon Enterprise Inc.",             Sector = "Industrials",            Exchange = "NASDAQ" },
            new() { Symbol = "NDAQ",  Name = "Nasdaq Inc.",                      Sector = "Financials",             Exchange = "NASDAQ" },
        };
    }
}
